#!/usr/bin/env bash

# Remove ignored files
git clean -Xdf

# Compile PDFs and copy into respective directories
for tex_file in *.tex
do
  pdflatex ${tex_file}
  name=${tex_file%%.*}
  pdf_file="${name}.pdf"
  hash_incipit=$(sha256sum $pdf_file | cut --characters=1-7)
  mkdir -p "${name}/"
  cp $pdf_file "${name}/${hash_incipit}.pdf"
done

# Print PDF hashes at the end
sha256sum *.pdf
