#!/usr/bin/env bash

# Compute pairwise diffs of */*.pdf

for directory in */
do
  cd ${directory}
  file_array=(*.pdf)
  file_count=${#file_array[@]}
  for ((i = 0; i < $file_count; i ++)); do
    file_i=${file_array[i]}
    name_i=${file_i%%.*}
    for ((j = i + 1; j < $file_count; j++)); do
      file_j=${file_array[j]}
      name_j=${file_j%%.*}
      diff \
        --unified \
        --text \
        --label $file_i \
        --label $file_j \
        -- $file_i $file_j \
        > "${name_i}-${name_j}.diff"
    done
  done
  cd ../
done
